name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests
      run: yarn test
    
    - name: Build project
      run: yarn build
    
    - name: Run linter with auto-fix
      run: yarn lint --fix
    
    - name: Run linter (final check)
      run: yarn lint

  # Alternative: Use a separate lint job with different config
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run linter with CI config
      run: |
        if [ -f .eslintrc.ci.js ]; then
          yarn eslint --config .eslintrc.ci.js --ext .ts src
        else
          yarn lint --fix || true
          yarn lint
        fi